export type BusinessType = {
    additional_information: null;
    additional_invoice_information: null | unknown;
    address_1: string;
    address_2: string;
    appointment_reminders_enabled: boolean;
    appointment_type_ids: [];
    archived_at: null;
    business_name: string;
    business_registration_name: string;
    business_registration_value: string;
    city: string;
    contact_information: string;
    country_code: string;
    country: string;
    created_at: Date | null;
    deleted_at: Date | null;
    display_name: string;
    email_reply_to: string;
    id: string;
    label: string;
    post_code: string;
    show_in_online_bookings: boolean;
    state: string;
    time_zone: string;
    time_zone_identifier: string;
    updated_at: Date;
    website_address: string;
    practitioners: unknown;
    appointments: unknown;
    links: unknown;
  };